# Generated by Django 3.0.5 on 2020-04-12 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('price', models.FloatField(blank=True, null=True)),
                ('date_added', models.DateField(auto_now=True)),
                ('jewelry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.JewelryType')),
            ],
        ),
    ]
