# Generated by Django 3.0.5 on 2020-04-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disc',
            field=models.TextField(null=True),
        ),
    ]
